language: ruby
rvm:
  - 1.8.7
script: "make test"
before_script:
  - sudo bin/ensure_puppet_version
env:
  - PUPPET_VERSION=3.3.0
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.9
