language: ruby
rvm:
  - 1.8.7
script: "make test"
before_script:
  - sudo PUPPET_VERSION=$PUPPET_VERSION FACTER_VERSION=$FACTER_VERSION bin/ensure_puppet_version
env:
  matrix:
    - PUPPET_VERSION=3.7.4 FACTER_VERSION=2.
    - PUPPET_VERSION=3.6.2 FACTER_VERSION=2.
    - PUPPET_VERSION=3.5.1 FACTER_VERSION=2.
    - PUPPET_VERSION=3.4.3 FACTER_VERSION=2.
    - PUPPET_VERSION=3.3.2 FACTER_VERSION=2.
    - PUPPET_VERSION=2.7.17 FACTER_VERSION=1.
    - PUPPET_VERSION=2.7.13 FACTER_VERSION=1.
